project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    left:
      - href: index.qmd
        icon: house-fill
        text: Home
      - href: gallery.qmd
        icon: search
        text: Gallery
      - href: software.qmd
        icon: code-slash
        text: Software

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - epicentre_qmd_style.scss
    toc: true
