project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    left:
      - href: about_index.qmd
        text: About
      - href: dashboard_index.qmd
        text: Dashboard Gallery
      - href: report_index.qmd
        text: Reports
      - href: pkg_index.qmd
        text: Packages

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
