project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Gallery

execute:
  freeze: auto

format:
  html: 
    theme: cosmo
    css: styles.css
    toc: true
