project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    background: primary
    left:
      - href: gallery.qmd
        icon: search
        text: Gallery
      - href: software.qmd
        icon: code-slash
        text: Software

execute:
  freeze: auto

format:
  html:
    theme:
      - default
      - styles.scss
    css: styles.css
    toc: true
