project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    background: light
    left:
      - href: gallery.qmd
        icon: search
        text: Gallery
      - href: https://epicentre-msf.github.io/outbreak-tools/
        icon: globe
        text: Outbreak Tools
      - href: https://epicentre-msf.r-universe.dev/packages
        icon: code-slash
        text: R Packages

execute:
  freeze: auto

format:
  html:
    theme:
      - default
      - styles.scss
    css: styles.css
    toc: true
