project:
  type: website

website:
  title: "Epicentre Data Science"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard & Reports Gallery
      - href: pkg.qmd
        text: R Packages

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - epicentre_qmd_style.scss
    toc: true
