---
page-layout: full
toc: false
listing:
  id: gallery
  template: epi-grid.ejs
  contents: items/gallery.yml
  categories: true
  page-size: 1000
  sort: 
    - "status" 
    - "date-modified desc"
  sort-ui: [title, date-created, date-modified]
  filter-ui: true
  field-required: [title, href, status, access, author, date-created, date-modified]
  field-types:
    date-created: date
    date-modified: date
  field-display-names:
    status: "Status"
    access: "Access"
    date-created: "Published"
    date-modified: "Updated"
---

## Data App Gallery

Below is our collection of our interactive dashboards, reports and tools. Use the search bar and categories menu to filter to your areas of interest.

Items labelled as [INTERNAL]{.tag .status-internal} will require a login. 

If you are a member of the MSF network you can use your MSF Microsoft365 account to log in. Note that some dashboards are limited to specific OCs, individual personel or project partners, so not all content will be accessible with your account.

External users working on an Epicentre/MSF related project requiring access to a dashboard, please speak with an Epicentre/MSF contant on your project and ask them to get in touch with the Epicentre Data Science Team, detailing the relevant dashboard(s) and list of email addresses that require access. 

---

::: {#gallery}
:::
